### PR TITLE
Fix missing env in compose

### PR DESCRIPTION
**Pull request by fguisso**
2 days debugging this problem to using horusec in another host. btw, you guys need to update this documentation: https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/

**- What I did**
Adding missing env in compose files.

**- Description for the changelog**
Adding missing env in compose files

### CODE REVIEW

**Comment by nathanmartinszup** [comment]
> 2 days debugging this problem to using horusec in another host. btw, you guys need to update this documentation: https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/
> 
> **- What I did**
> Adding missing env in compose files.
> 
> **- Description for the changelog**
> Adding missing env in compose files

Hi, @fguisso.

To accept your pull request, I need it to be verified by a GPG key as well as signed `git commit --signoff`.

**Comment by nathanmartinszup** [comment]
> 2 days debugging this problem to using horusec in another host. btw, you guys need to update this documentation: https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/
> 
> **- What I did**
> Adding missing env in compose files.
> 
> **- Description for the changelog**
> Adding missing env in compose files

@fguisso 

Still missing signed off commit.
Can be done with `-s` flag: ex: `git commit -s` or `git commit --signoff`

Your commit should contain your name and email: 
EX: ` Signed-off-by: nathanmartinszup <nathan.martins@zup.com.br >`

**Comment by fguisso** [comment]
https://github.com/ZupIT/horusec-platform/pull/123/commits
Screen Shot 2021-07-14 at 18 46 20

obs: I don't know why no core contributors needs to sign in the commit, you can resolve that by co-authored the commit and sign in by one core committer.

**Comment by nathanmartinszup** [comment]
> https://github.com/ZupIT/horusec-platform/pull/123/commits
> Screen Shot 2021-07-14 at 18 46 20
> 
> obs: I don't know why no core contributors needs to sign in the commit, you can resolve that by co-authored the commit and sign in by one core committer.

From now on, all commits must follow the DCO rules. It's necessary that all are signed and contains a verified signature.

Here is an example:

dco

`git commit -s --amend` will fix it.

**Review by nathanmartinszup — APPROVED** [review]

**Pull request merged**
