### PR TITLE
Add uri.scheme

### PR DESCRIPTION
**Pull request by safe2008**
**- What I did**
- Fix the auth.yaml
- Add manager.uri.scheme and auth.uri.scheme

**- How to verify it**
- helm install horusec-platform -f deployments/helm/horusec-platform/values.yaml deployments/helm/horusec-platform -n horusec-system-test --dry-run

**- Description for the changelog**

### CODE REVIEW

**Review by tiagoangelozup — APPROVED** [review]
Hello there! Thanks for the PR ;)

**Comment by wiliansilvazup** [comment]
Thanks for your feedback @safe2008 !
It is helping us a lot with the product, remembering that if you need any additional support you can contact us through the email horusec@zup.com.br or through our open source forum https://forum.zup.com.br/

**Review by wiliansilvazup — APPROVED** [review]

**Comment by safe2008** [comment]
> Thanks for your feedback @safe2008 !
> It is helping us a lot with the product, remembering that if you need any additional support you can contact us through the email [horusec@zup.com.br](mailto:horusec@zup.com.br) or through our open source forum https://forum.zup.com.br/

Do you have slack channel?

**Comment by wiliansilvazup** [comment]
we don't have a channel on slack 😞,  but in our forum is free 😄 you can sign up and contact us over there!

**Pull request merged**
